### ISSUE TITLE
zCustomFunction doesn't return a type when using runMutation/runQuery etc.

### ISSUE THREAD

**Issue by MatteusSteinberg** [get-convex/convex-helpers#504]
Since updating to Convex 1.20^ it has become "illegal" to execute Convex functions as a normal Typescript function ( await fooBar(ctx, { args }) ) so the only correct approach is to run internal and external functions with the action helpers ( await runQuery(internal.foo.bar.fooBar, { args }) )

When running runMutation(api/internal....) for a **zCustomFunction** it returns **`any`**, but when using the default built-in Convex function, the correct types get returned. 

Example of failing/missing type actions:

**/searchAgent/external.ts**
```
import { action } from '../utils/customWrapper'
import { internal } from '../_generated/api'

export default action({
  args: {
    searchAgentId: zid('searchAgents')
  },
  handler: async (ctx, { searchAgentId }) => {
    const { runQuery } = ctx
    return  await runQuery(internal.searchAgent.index.get, { searchAgentId })
  }
})
```

**/searchAgent/index.ts**
```
import { zid } from 'convex-helpers/server/zod'
import { internalQuery } from '../utils/customWrapper'

export const get = internalQuery({
  args: {
    searchAgentId: zid('searchAgents')
  },
  handler: async (ctx, { searchAgentId }) => {
    const { db } = ctx

    const searchAgent = await db.get(searchAgentId)

    return searchAgent
  }
})

```

**/utils/customWrapper.ts**
```
import { zCustomAction, zCustomMutation, zCustomQuery } from 'convex-helpers/server/zod'
import { v } from 'convex/values'
import {
  action as convexAction,
  internalAction as convexInternalAction,
  internalMutation as convexInternalMutation,
  internalQuery as convexInternalQuery,
  mutation as convexMutation,
  query as convexQuery
} from '../_generated/server'

export const mutation = zCustomMutation(convexMutation, {
  args: {
    posthogDistinctId: v.optional(v.string())
  },
  input: async (ctx, { posthogDistinctId }) => {
    return { ctx: { ...ctx, posthogDistinctId }, args: {} }
  }
})

export const query = zCustomQuery(convexQuery, {
  args: {
    posthogDistinctId: v.optional(v.string())
  },
  input: async (ctx, { posthogDistinctId }) => {
    return { ctx: { ...ctx, posthogDistinctId }, args: {} }
  }
})

export const action = zCustomAction(convexAction, {
  args: {
    posthogDistinctId: v.optional(v.string())
  },
  input: async (ctx, { posthogDistinctId }) => {
    return { ctx: { ...ctx, posthogDistinctId }, args: {} }
  }
})

export const internalMutation = zCustomMutation(convexInternalMutation, {
  args: {
    posthogDistinctId: v.optional(v.string())
  },
  input: async (ctx, { posthogDistinctId }) => {
    return { ctx: { ...ctx, posthogDistinctId }, args: {} }
  }
})

export const internalQuery = zCustomQuery(convexInternalQuery, {
  args: {
    posthogDistinctId: v.optional(v.string())
  },
  input: async (ctx, { posthogDistinctId }) => {
    return { ctx: { ...ctx, posthogDistinctId }, args: {} }
  }
})

export const internalAction = zCustomAction(convexInternalAction, {
  args: {
    posthogDistinctId: v.optional(v.string())
  },
  input: async (ctx, { posthogDistinctId }) => {
    return { ctx: { ...ctx, posthogDistinctId }, args: {} }
  }
})
```

**Comment by ianmacartney** [comment]
I'll take a look at this later on. But one note:
If the calling function is an action, you've always needed to use runQuery
/ runMutation since the action isn't in a transaction and doesn't have
access to the database (ctx.db doesn't exist).
But for mutations calling mutation/query, or a query calling a query, I'd
recommend pulling out the functions into helper functions instead of doing
`runQuery / runAction`.
Since it's just more overhead to do `runQuery`/`runMutation` as they start
a new subtransaction in a new isolated function (unless you need
subtransactions which is more rare)

https://docs.convex.dev/understanding/best-practices/#use-helper-functions-to-write-shared-code

**Comment by ianmacartney** [comment]
Also, I just released `0.1.73` which updates the zod helpers and allows you
to specify `returns` validators which may help with the type inference when
TypeScript gives up

**Comment by MatteusSteinberg** [comment]
Any update on this?

**Comment by ianmacartney** [comment]
> Any update on this?

@MatteusSteinberg - it should be fixed in the latest version of `convex-helpers`. Please re-open if not!

**Comment by MatteusSteinberg** [comment]
@ianmacartney - I'm running v0.1.75 and the type is still not inferred

**Comment by ianmacartney** [comment]
Sorry to hear that, I can try to reproduce it again later this week, but it was working for me. If you made a repo with a minimal reproduction it'd be quicker to debug. Thanks!

**Comment by ianmacartney** [comment]
@MatteusSteinberg the issue you're seeing is due to circular type references, not due to the zod helpers. I copied your functions into a project and you don't get the issue if you take out this:
```ts
return  await runQuery(internal.searchAgent.index.get, { searchAgentId })
```

Unfortunately even though they're in different files, they all import from `api` which imports from all the files, so when their output type depends on another function's output type it get tough. You can break the cycle by annotating the return type of the function like this:

```ts
export default action({
  args: {
    searchAgentId: zid("searchAgents"),
  },
  handler: async (ctx, { searchAgentId }): Promise<Doc<"searchAgents"> | null> => {
    const { runQuery } = ctx;
    return await runQuery(internal.zodExample.get, { searchAgentId });
  },
});
```

**Comment by MatteusSteinberg** [comment]
This tanks the developer experience of using the zod helpers if I have to run through my whole codebase and start annotating the return type for each function manually.

Do you plan on having the issue fixed or will it be like this for the foreseeable future if I want to use the zod helpers?

**Comment by ianmacartney** [comment]
This is not specific to the zod helper, this is due to the global api
object. Does specifying a returns validator break the cycle for you? I
haven’t put energy into that but for people who want to do return
validation that could be another way to break the cycle.
I have some ideas for workarounds to segment the types but again it is not
specific to  the zod helper, just to Convex overall.
You only need to annotate functions when their return type depends on other
functions

**Comment by ianmacartney** [comment]
I thought it should work when you break it up between files, maybe my repro
wasn’t the best because the function defs I think were in the one of the
files.

**Comment by MatteusSteinberg** [comment]
I have split the code into multiple files and still have the same issue where no type is returned from the function. I've tried breaking up the dependencies across different files as suggested, setting a return validator, annotating a return type but I'm still experiencing the same problem with the type information not being properly propagated.

Why should the issue be circular dependency?

**Comment by ianmacartney** [comment]
Here's some resources:
https://docs.convex.dev/functions/actions#dealing-with-circular-type-inference
https://github.com/get-convex/convex-js/issues/3
https://discord.com/channels/1019350475847499849/1195158111665799248

Here's a repro with your code that I fixed by adding a return type: https://github.com/get-convex/convex-helpers/blob/repro/zod-return-type/convex/zod2.ts#L21
So I'm guessing it's some return type that needs to get annotated. You can bisect the issue by commenting out code. 

The cycle is 
1. function A export depends on value of `internal.foo.otherFunction`.
2. `internal` depends on every file export.
3. file export type depends on function A export.

There are efforts to do some static codegen to break the cycle, and I have other ideas, but this is how it works currently. Sorry!

**Comment by ianmacartney** [comment]
I can't repro the issue after annotating the `handler` type. I've noted the issue with Convex. This is a known paper-cut we hope to address, and have some work started for, including codegen to break the cycle using a convex.json parameter

let me know if there's a repo with a repro. sorry this caused so much headache for you
